import Foundation

public struct ChannelObject: Decodable {
    public var author: String
    public var authorId: String
    public var authorUrl: String
    public var authorVerified: Bool
    public var authorBanners: [ImageObject]
    public var authorThumbnails: [ImageObject]
    public var subCount: Int
    public var totalViews: Int
    public var joined: Int
    public var autoGenerated: Bool
    public var isFamilyFriendly: Bool
    public var description: String
    public var descriptionHtml: String
    public var allowedRegions: [String]
    public var latestVideos: [VideoObject]
    public var relatedChannels: [ChannelObject]
    
    public static func == (lhs: ChannelObject, rhs: ChannelObject) -> Bool {
        lhs.authorId == rhs.authorId
    }
}
